// import-pets.mjs — 把旧版 pets.js 的 ALL_PETS 数据导出为 TS 数据文件
// 用法: cd poc-phaser && node scripts/import-pets.mjs

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(__dirname, '../../games/turtle-battle/js/pets.js');
const OUT = resolve(__dirname, '../src/data/pets.ts');

let code = readFileSync(SRC, 'utf8');

// 旧版定义 PET_SYNERGY_TAGS 也在 pets.js 里, 一起拿
code += '\n;globalThis.__OUTPUT__ = { ALL_PETS, PET_SYNERGY_TAGS, RARITY_MULT, DEF_CONSTANT };';

const ctx = vm.createContext({ globalThis: {}, console });
vm.runInContext(code, ctx);
const { ALL_PETS, PET_SYNERGY_TAGS, RARITY_MULT, DEF_CONSTANT } = ctx.globalThis.__OUTPUT__;

// 中文 PNG → ASCII 别名映射 (跟 sync-public.mjs:60-71 一一对应)
// 用 ASCII 是因为 Vercel CDN 对 Unicode 文件名兼容差 (deploy 后 404).
// sync-public.mjs 在 build 时把每个中文 PNG 复制一份成 ASCII 别名, 这里 pets.ts
// 引用 ASCII 即可两端都通: 本地 Vite + Vercel 都 serve ASCII 文件.
const CHINESE_TO_ASCII = {
  'pets/石头龟v1.png': 'pets/stone.png',
  'pets/竹叶龟v1.png': 'pets/bamboo.png',
  'pets/天使龟v1.png': 'pets/angel.png',
  'pets/寒冰龟.png': 'pets/ice.png',
  'pets/双头龟.png': 'pets/two_head.png',
  'pets/钻石龟.png': 'pets/diamond.png',
  'pets/财神龟v1.png': 'pets/fortune.png',
  'pets/骰子龟v1.png': 'pets/dice.png',
  'pets/彩虹龟.png': 'pets/rainbow.png',
  'pets/赌神龟v1.png': 'pets/gambler.png',
  'pets/猎人龟v1.png': 'pets/hunter.png',
  'pets/海盗龟.png': 'pets/pirate.png',
  'pets/糖果龟v1.png': 'pets/candy.png',
  'pets/气泡龟v1.png': 'pets/bubble.png',
  'pets/线条龟v1.png': 'pets/line.png',
  'pets/闪电龟.png': 'pets/lightning.png',
  'pets/凤凰龟.png': 'pets/phoenix.png',
  'pets/熔岩龟.png': 'pets/lava.png',
  'pets/赛博龟.png': 'pets/cyber.png',
  'pets/水晶龟v1.png': 'pets/crystal.png',
  'pets/宝箱龟v1.png': 'pets/chest.png',
  'pets/星际龟v1.png': 'pets/space.png',
  'pets/缩头乌龟v1.png': 'pets/hiding.png',
  'pets/无头龟v1.png': 'pets/headless.png',
  'pets/龟壳v1.png': 'pets/shell.png',
};

// 路径规范化:
// 1. 去 "../../" + "assets/" 前缀 (Phaser publicDir 已指 assets/)
// 2. 中文 PNG → ASCII 别名 (sync-public 已 build-time 复制了 ASCII 副本)
//    旧版尝试 encodeURI 中文路径在 Vercel CDN 上仍 404, 原因是部分 CDN 不
//    persist UTF-8 文件名, 改 ASCII 是真正稳的方案.
function normalizeAssetPath(p) {
  if (typeof p !== 'string') return p;
  const stripped = p
    .replace(/^\.\.\/\.\.\//, '')   // "../../assets/..." → "assets/..."
    .replace(/^assets\//, '');        // "assets/..." → "..."
  // 优先查 ASCII 别名表
  if (CHINESE_TO_ASCII[stripped]) return CHINESE_TO_ASCII[stripped];
  return stripped;
}

function walk(v) {
  if (Array.isArray(v)) return v.map(walk);
  if (v && typeof v === 'object') {
    const out = {};
    for (const [k, val] of Object.entries(v)) {
      if (k === 'img' || k === 'src') out[k] = normalizeAssetPath(val);
      else out[k] = walk(val);
    }
    return out;
  }
  return v;
}

// P126: 用户规则修改 — 全员 +100 耐久度 baked 进基础 hp.
//   仅对顶层 pet (id/name/rarity/hp 同级) 的 hp 字段加 100, 不影响 passive.hpPct/
//   shieldHpPct 等子字段. import 阶段统一处理, 保证 pets.ts 出来就是 +100 后的值.
function applyEnduranceBuff(pets) {
  for (const pet of pets) {
    if (typeof pet.hp === 'number') pet.hp += 100;
  }
}
applyEnduranceBuff(ALL_PETS);

const normalized = walk(ALL_PETS);

// 写 TS
const json = JSON.stringify(normalized, null, 2);

const header = `// AUTO-GENERATED by scripts/import-pets.mjs — DO NOT EDIT MANUALLY
// 旧版 /games/turtle-battle/js/pets.js → ALL_PETS 的 TS 镜像
// 路径已归一化: 去掉 "../../" 和 "assets/" 前缀, 配合 Phaser publicDir 使用
import type { PetDef } from '../types';

export const RARITY_MULT = ${JSON.stringify(RARITY_MULT)} as const;
export const DEF_CONSTANT = ${DEF_CONSTANT};

export const PET_SYNERGY_TAGS = ${JSON.stringify(PET_SYNERGY_TAGS, null, 2)} as const;

export const ALL_PETS: PetDef[] = ${json};

export const PET_BY_ID: Record<string, PetDef> = Object.fromEntries(
  ALL_PETS.map(p => [p.id, p])
);
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, header, 'utf8');
console.log(`✓ Wrote ${OUT} — ${ALL_PETS.length} pets`);
