// AUTO-GENERATED by scripts/import-equipment.mjs — DO NOT EDIT MANUALLY
// 旧版 /games/turtle-battle/js/engine.js EQUIP_POOL 镜像
// apply() 直接改 Fighter 上的数值字段; 跨文件 helper (recalcStats 等) 由本文件 stub 兜底。
/* eslint-disable @typescript-eslint/no-explicit-any */
import type { EquipmentDef, Fighter } from '../types';

// ── stub: 旧版 apply() 引用的外部 helper, PoC 阶段先 noop ────
// recalcStats: 触发数值重算 (Phase A 暂时 BattleScene 自己 recalc, 这里不动)
const recalcStats: () => void = () => {};
// P141: applyHeal 之前是空 stub (..._args)=>0 → c_heal/c_firstaid 调它啥也不干,
//   治疗药水/急救包完全不治疗! 现按 JS engine.js:1022 真实现 (消耗品 apply 运行时确实调用).
const applyHeal = (target: Fighter, amount: number, _label?: unknown): number => {
  void _label;
  if (!target) return 0;
  const t = target as Fighter & {
    _undeadLockTurns?: number; _equipRippleHealAmp?: number;
    _synergyGuardAmp?: number; _equipStarOverflow?: number;
  };
  if ((t._undeadLockTurns ?? 0) > 0) return 0;   // 锁血 1HP 不治疗
  const healRed = target.buffs?.find(b => b.type === 'healReduce');
  if (healRed) amount = Math.round(amount * (1 - (healRed.value ?? 0) / 100));
  if (t._equipRippleHealAmp) amount = Math.round(amount * (1 + t._equipRippleHealAmp / 100));
  if (t._synergyGuardAmp) amount = Math.round(amount * (1 + t._synergyGuardAmp));
  const before = target.hp;
  target.hp = Math.min(target.maxHp, target.hp + amount);
  const actual = Math.round(target.hp - before);
  if (t._equipStarOverflow) {
    const overflow = amount - actual;
    if (overflow > 0) {
      const shieldGain = Math.round(overflow * t._equipStarOverflow / 100);
      if (shieldGain > 0) target.shield = (target.shield || 0) + shieldGain;
    }
  }
  return actual;
};
const applyRawDmg = (..._args: unknown[]) => ({ hpLoss: 0, shieldAbs: 0 });
const triggerDragonFly = (_f: Fighter) => {};
const getFighterElId = (_f: Fighter) => '';
const updateHpBar = (..._args: unknown[]) => {};
const renderStatusIcons = (_f: Fighter) => {};
const applyHeal2 = (_f: Fighter, _amt: number, _opts?: unknown) => 0;

export const EQUIP_POOL: EquipmentDef[] = [
  // ── Stat boost (6) ──
  { id:'e_blade', name:'海藻短刃', icon:'equip/dungeon-blade.png', category:'normal',
    desc:'提供 +20 攻击力。\n流血:\n携带者普通攻击命中敌人后, 对其施加 (0.075×ATK) 的流血层数。',
    apply(f: any) {
      f.baseAtk += 20; f.atk = f.baseAtk;
      f._equipBladeBleed = 2;            // 命中后施加 2 回合流血 (combat.js on-hit 处理)
    } },
  { id:'e_carapace', name:'珊瑚硬壳', icon:'equip/dungeon-armor.png', category:'normal',
    desc:'提供 +60 最大生命值。\n硬化:\n携带者每次受到伤害时, 获得一层硬化层数, 每层为其提供 +1 护甲和 +1 魔抗, 至多提供 +20 护甲和 +20 魔抗。\n达到最大层数时, 携带者立即获得 40 点永久护盾值。',
    apply(f: any) {
      f.maxHp += 60; f.hp += 60;
      if (typeof f._equipCarapaceGain !== 'number') f._equipCarapaceGain = 0;
      // 多件 → cap +20 / 件, shieldGiven 也按件数重置, 让满层护盾累计触发
      f._equipCarapaceCap = (f._equipCarapaceCap || 0) + 20;
      f._equipCarapaceShieldGiven = false;
    } },
  { id:'e_pearl', name:'生命珍珠', icon:'equip/dungeon-pearl.png', category:'unique',
    desc:'提供 +20 最大生命值, +4 护甲, +4 魔抗。\n珍珠:\n携带者生命值首次降至 50% 以下时触发。\n使携带者立即回复 20% 最大生命值, 并向 1 名随机敌人发射一颗火球, 造成 (8% 目标最大生命值) 魔法伤害, 并对目标施加 30 灼烧层数。\n触发完成后装备销毁。',
    apply(f: any) {
      f.maxHp += 20; f.hp += 20;
      f.baseDef += 4; f.def = f.baseDef;
      f.baseMr = (f.baseMr || f.baseDef) + 4; f.mr = f.baseMr;
      f._equipPearl = true;
      // HP 已经 <50% 则下一次受伤直接触发（state.js subscriber 处理）
    } },
  { id:'e_tooth', name:'锋利鲨齿', icon:'equip/dungeon-tooth.png', category:'normal',
    desc:'提供 +8 攻击力, +5 护甲穿透, +25% 暴击率。',
    apply(f: any) {
      f.baseAtk += 8; f.atk = f.baseAtk;
      f.armorPen += 5;
      f.crit += 0.25;
    } },
  { id:'e_hammer', name:'重击锤', icon:'equip/dungeon-hammer.png', category:'normal',
    desc:'提供 +100 最大生命值。\n压力:\n携带者获得相当于 4% 携带者最大生命值的攻击力。',
    unique: false,  // 叠加：每件 +100maxHp，且 _equipHammer 计数让 atk 加成 ×N
    apply(f: any) {
      f.maxHp += 100; f.hp += 100;
      f._equipHammer = (f._equipHammer || 0) + 1;
      // 攻击力加成在 recalcStats 里实时算 → 触发一次刷新
      if (typeof recalcStats === 'function') recalcStats();
    } },
  { id:'e_piercer', name:'双穿珊瑚刺', icon:'equip/dungeon-spike.png', category:'normal',
    desc:'提供 +8 攻击力, +6 护甲穿透, +6 魔法穿透。',
    apply(f: any) {
      f.baseAtk += 8; f.atk = f.baseAtk;
      f.armorPen += 6; f.magicPen = (f.magicPen||0) + 6;
    } },

  // ── Special effect (12) ──
  { id:'e_star', name:'生命偷取海星', icon:'equip/dungeon-starfish.png', category:'unique',
    desc:'提供 +12% 生命偷取。\n汲取:\n携带者受到的溢出治疗部分会以 50% 比例转化为护盾值。\n※ 任何来源的治疗',
    apply(f: any) {
      f._lifestealPct = (f._lifestealPct||0) + 12;
      f._equipStarOverflow = 50;         // applyHeal 里回血溢出 maxHp 部分 ×50% → shield
    } },
  { id:'e_urchin', name:'荆棘海胆', icon:'equip/dungeon-urchin.png', category:'normal',
    desc:'提供 +50 最大生命值, +10% 反伤。',
    apply(f: any) {
      f.maxHp += 50; f.hp += 50;
      f._equipReflect = (f._equipReflect||0) + 10;
    } },
  { id:'e_fire', name:'灼热火珊瑚', icon:'equip/dungeon-fire-coral.png', category:'unique',
    desc:'提供 +50 最大生命值。\n火珊瑚:\n携带者施法结束时, 对本次施法造成过伤害的每个敌人施加 20 层灼烧。',
    apply(f: any) {
      f.maxHp += 50; f.hp += 50;
      f._equipBurn = true;
    } },
  { id:'e_jelly', name:'冰封水母', icon:'equip/dungeon-jelly.png', category:'unique',
    desc:'提供 +20 最大生命值, +5 护甲。\n冰冻:\n携带者攻击命中敌人时, 有 25% 概率使该目标眩晕 1 回合。',
    apply(f: any) {
      f.maxHp += 20; f.hp += 20;
      f.baseDef += 5; f.def = f.baseDef;
      f._equipStun = 25;
    } },
  { id:'e_anemone', name:'治愈海葵', icon:'equip/dungeon-anemone.png', category:'normal',
    desc:'提供 +5 护甲, +10 魔抗。\n治愈:\n携带者每回合开始时回复 8% 最大生命值。',
    apply(f: any) {
      f.baseDef += 5; f.def = f.baseDef;
      f.baseMr = (f.baseMr || f.baseDef) + 10; f.mr = f.baseMr;
      f._equipHot = (f._equipHot || 0) + 8;
    } },
  { id:'e_ghost', name:'幽灵墨鱼', icon:'equip/dungeon-ghost.png', category:'unique',
    desc:'提供 +20 最大生命值, +15% 闪避率。\n幽灵:\n携带者每次成功闪避一次攻击时, 立即获得 20 点永久护盾值。',
    apply(f: any) {
      f.maxHp += 20; f.hp += 20;
      f.buffs.push({type:'dodge', value:15, duration:999});  // P141b turns→duration (PoC 靠 duration 过期; 999=永久)
      f._equipGhostSquid = true;
    } },
  { id:'e_octo', name:'暗袭章鱼爪', icon:'equip/dungeon-octo.png', category:'normal',
    desc:'提供 +15 攻击力。\n长爪:\n携带者对后排敌人造成的伤害额外 +20%。',
    apply(f: any) {
      f.baseAtk += 15; f.atk = f.baseAtk;
      f._equipBackrowBonus = (f._equipBackrowBonus || 0) + 20;
    } },
  { id:'e_conch', name:'复活海螺', icon:'equip/dungeon-conch.png', category:'unique',
    desc:'提供 +100 最大生命值。\n小虫形态:\n携带者彻底阵亡 (所有复活机会用尽) 时触发。\n在原位置变形为一只小虫 (150 HP, 20 攻击力, 无护甲魔抗, 等级每级 +5% 属性), 每回合自动攻击当前生命值最低的敌人, 造成 1×ATK 物理伤害。',
    apply(f: any) {
      f.maxHp += 100; f.hp += 100;
      f._equipConch = true;
    } },
  { id:'e_ripple', name:'潮汐涟漪', icon:'equip/dungeon-shell.png', category:'normal',
    desc:'提供 +100 最大生命值, +30% 护盾和治疗强度。\n涟漪:\n每回合开始时, 为全体己方友军 (含携带者) 回复其当前已损失生命值的 3%。',
    apply(f: any) {
      f.maxHp += 100; f.hp += 100;
      // 改可叠加: 多件 ripple 时 healAmp / allyHotPct 全部加总
      f._equipRippleHealAmp = (f._equipRippleHealAmp || 0) + 30;
      f._equipRippleAllyHotPct = (f._equipRippleAllyHotPct || 0) + 3;
    } },
  { id:'e_dragon_egg', name:'龙蛋', icon:'equip/dungeon-dragon-egg.png', category:'unique',
    desc:'提供 +8 攻击力, +5 魔法穿透。\n吐息:\n携带者每回合开始时获得 1 层吐息层数。达到 3 层时, 立即召唤一条喷火龙沿一排 (随机选有敌人的列) 飞过 — 火焰会对接触的己方单位回复 40 生命值, 对接触的敌方单位造成 50 魔法伤害并施加 25 灼烧层数, 随后重置吐息层数。\n装备时立即获得 3 层吐息。',
    apply(f: any) {
      f.baseAtk += 8; f.atk = f.baseAtk;
      f.magicPen = (f.magicPen || 0) + 5;
      f._equipDragonEgg = true;
      f._equipDragonEggStacks = 3;
      // 装上瞬间触发一次喷火龙 → 重置层数 (用 setTimeout 避开 apply 同步路径)
      setTimeout(() => {
        if (typeof triggerDragonFly === 'function' && f.alive) {
          triggerDragonFly(f);
          f._equipDragonEggStacks = 0;
        }
      }, 600);
    } },
  { id:'e_mini_crystal', name:'迷你水晶球 A', icon:'equip/dungeon-mini-crystal.png', category:'unique',
    desc:'提供 +7 攻击力, +20 最大生命值, +5 魔法穿透。\n魔法光线:\n回合末从携带者位置朝随机敌人方向发射一道魔法光线, 沿同一列穿过造成两段伤害。每段为 30 魔法伤害并施加 1 层迷你水晶。\n迷你水晶层数:\n拥有 3 层迷你水晶层数的敌人会被立即引爆, 受到 (14% 目标最大生命值) 魔法伤害, 并重置该敌人的迷你水晶层数。',
    apply(f: any) {
      f.maxHp += 20; f.hp += 20;
      f.magicPen = (f.magicPen || 0) + 5;
      f.baseAtk += 7; f.atk = f.baseAtk;
      f._equipMiniCrystal = true;
    } },
  { id:'e_mini_crystal_b', name:'迷你水晶球 B', icon:'equip/dungeon-mini-crystal-b.png', category:'unique',
    desc:'提供 +7 攻击力, +3 魔法穿透, +20 最大生命值。\n激光:\n回合末以携带者为中心, 射出一道红光朝全体敌方扫过。红光触碰到每个存活敌人时, 对其造成 20 魔法伤害并施加 1 层迷你水晶。\n迷你水晶层数:\n拥有 3 层迷你水晶层数的敌人会被立即引爆, 受到 (14% 目标最大生命值) 魔法伤害, 并重置该敌人的迷你水晶层数。',
    apply(f: any) {
      f.maxHp += 20; f.hp += 20;
      f.magicPen = (f.magicPen || 0) + 3;
      f.baseAtk += 7; f.atk = f.baseAtk;
      f._equipMiniCrystalB = true;
    } },
  { id:'e_thunder_shell', name:'雷鸣贝壳', icon:'equip/dungeon-crystal.png', category:'normal',
    desc:'提供 +15 攻击力。\n电击:\n携带者自己回合结束时, 电击 1 名随机敌人, 造成 1×ATK 真实伤害。',
    apply(f: any) {
      f.baseAtk += 15; f.atk = f.baseAtk;
      f._equipThunderBell = (f._equipThunderBell || 0) + 1;
    } },
  { id:'e_hourglass', name:'沙漏', icon:'equip/dungeon-hourglass.png', category:'unique',
    desc:'时间:\n携带者所有技能的基础冷却时间永久 -1 回合。\n※ 最低 0 cd, 只有携带时这件装备才生效',
    apply(f: any) {
      if (f.skills && f.skills.length) {
        for (const s of f.skills) {
          if (typeof s.cd !== 'number') continue;
          if (typeof s._hourglassOrigCd !== 'number') s._hourglassOrigCd = s.cd;  // 存原 cd 供未来移除装备时还原
          s.cd = Math.max(0, s.cd - 1);
        }
      }
      f._equipHourglass = true;
    } },
  { id:'e_dumbbell', name:'哑铃', icon:'equip/dungeon-dumbbell.png', category:'unique',
    desc:'提供 +100 最大生命值, +3 护甲, +3 魔抗。\n锻炼:\n携带者每回合开始时进行锻炼, 获得 +25 最大生命值。\n※ 深海闯关模式下: 锻炼累计仅本场战斗有效, 跨关重置归零。\n投掷:\n携带者在回合末向随机敌人扔出哑铃, 造成 (5% × 携带者当前最大生命值) 物理伤害。',
    apply(f: any) {
      f.maxHp += 100; f.hp += 100;
      f.baseDef += 3; f.def = f.baseDef;
      f.baseMr = (f.baseMr || f.baseDef) + 3; f.mr = f.baseMr;
      f._equipDumbbell = true;
      f._equipDumbbellGain = 0;  // 累计 +maxHp 显示用 (战斗内)
    } },
  { id:'e_fpga', name:'数字电路 FPGA 板', icon:'equip/dungeon-fpga.png', category:'unique',
    desc:'提供 +50 最大生命值。\n携带者每回合开始时随机抽取一个 2-bit 状态 (00 / 01 / 10 / 11), 当回合生效。\n状态 00:\n立即回复 5% 最大生命值, 并永久 +2 护甲 / +2 魔抗。\n状态 01:\n永久 +5 攻击力, 永久 +4% 生命偷取。\n状态 10:\n当回合获得 +15% 增伤。\n状态 11:\n当回合受到的所有伤害 -25% (持续 1 回合)。\n伤害减免不包括真实伤害',
    apply(f: any) {
      f.maxHp += 50; f.hp += 50;
      f._equipFpga = true;
    } },
  { id:'e_amplifier', name:'模拟电路信号放大器', icon:'equip/dungeon-amplifier.png', category:'unique',
    desc:'提供 +50 最大生命值。\n放大器:\n携带者每回合开始时获得 16%~24% 临时增伤。',
    apply(f: any) {
      f.maxHp += 50; f.hp += 50;
      f._equipAmplifier = true;
    } },
  { id:'e_candle', name:'蜡烛', icon:'equip/dungeon-candle-off.png', category:'unique',
    desc:'提供 +10 攻击力, +50 最大生命值。\n蜡烛在 3 个阶段间循环, 每回合末触发效果并切换阶段。\n熄灭阶段:\n无效果。\n微弱阶段:\n回合末携带者回复 20 生命值, 并治疗同一队邻格友军 10 生命值。\n燃烧阶段:\n回合末随机选 1 名敌人, 对其所在横排各单位造成 30 魔法伤害, 并施加 20 灼烧层数。',
    apply(f: any) {
      f.baseAtk += 10; f.atk = f.baseAtk;
      f.maxHp += 50; f.hp += 50;
      f._equipCandle = true;
      f._equipCandleStage = 0;  // 0=熄灭, 1=微弱, 2=燃烧
    } },
  { id:'e_revolver', name:'左轮手枪', icon:'equip/dungeon-revolver.png', category:'unique',
    desc:'提供 +10 攻击力, +5 护甲穿透。\n弹药:\n装备时获得 6 发子弹。\n任何敌人阵亡时, 左轮手枪获得 1 发子弹 (上限 6 发)。\n射击:\n携带者每回合末向 1 名随机敌人射出 1 颗子弹, 命中后造成 40 物理伤害。\n子弹为 0 时停止射击。\n※ 子弹为 0 时装备不会消失',
    apply(f: any) {
      f.baseAtk += 10; f.atk = f.baseAtk;
      f.armorPen = (f.armorPen || 0) + 5;
      f._equipRevolver = true;
      f._equipRevolverBullets = 6;
    } },
  { id:'e_laser_blade', name:'激光长刃', icon:'equip/dungeon-laser-blade.png', category:'unique',
    desc:'提供 +15 攻击力。\n携带者获得 "横扫" 技能。\n"横扫":\n选择敌方一列, 对该列每名敌人造成 0.7×ATK 物理伤害; 若该列仅 1 名存活敌人, 伤害提升至 1.4×ATK。\n携带者回复相当于横扫伤害的 80% 生命值。\n※ 冷却 0 回合',
    apply(f: any) {
      f.baseAtk += 15; f.atk = f.baseAtk;
      f._equipLaserBlade = true;
      // 加技能到 skills 数组
      if (Array.isArray(f.skills)) {
        f.skills.push({
          name:'横扫', type:'laserSweep', hits:1, power:0, pierce:0, cd:0, cdLeft:0, dmgType:'physical', _fromEquip:'e_laser_blade',
          brief:'对敌方一列 (F0/F1/F2 或 B0/B1/B2 整行) 各 <span class="val-atk">0.7×ATK</span> 物理；只命中 1 名 <span class="val-atk">1.4×ATK</span>。<span class="val-heal">回复造伤的 80%</span>',
          detail:'激光长刃横扫. 对目标所在 "列" (前排 3 个 / 后排 3 个) 同时挥砍:\n· 多目标命中: 每个敌人 <span class="val-atk">70%×攻击力({ATK}) = {N:0.7*ATK}</span> 物理\n· 单目标命中 (只 1 名): <span class="val-atk">140%×攻击力({ATK}) = {N:1.4*ATK}</span> 物理\n\n携带者回血 = 造成总伤害 × <span class="val-heal">80%</span>.\n冷却 0 回合.'
        });
      }
    } },
  { id:'e_doll', name:'玩偶小熊', icon:'equip/dungeon-doll.png', category:'unique',
    desc:'提供 +5 攻击力, +30 最大生命值。\n小熊攻击:\n携带者每回合末, 一只玩偶小熊从其位置走向随机敌人 (前排优先), 造成 30 物理伤害。携带者获得 1 层大熊层数。\n大熊:\n大熊层数达到或超过 5 后, 该装备销毁, 并在空位召唤一只大熊登场加入战斗。大熊拥有 250 生命值和 50 攻击力。\n※ 若己方阵营没有空位, 则继续小熊攻击, 直到有空位可以放置召唤物',
    apply(f: any) {
      f.baseAtk += 5; f.atk = f.baseAtk;
      f.maxHp += 30; f.hp += 30;
      f._equipDoll = true;
      f._equipDollBigBearStacks = 0;
      f._equipDollSpawned = false;
    } },
  { id:'e_dart', name:'飞镖', icon:'equip/dungeon-dart.png', category:'unique',
    desc:'提供 +15 攻击力。\n靶子标记:\n任何敌人本回合被己方"击飞"过 (击飞标签来自龟派气波 / 玩偶熊强化锤击 等技能) 即获得"靶子"状态。\n飞镖:\n携带者回合末向所有带靶子状态的敌人各射 1 枚飞镖, 命中造成 50 物理伤害并施加 20 流血层数, 命中后移除该敌人的靶子状态。',
    apply(f: any) {
      f.baseAtk += 15; f.atk = f.baseAtk;
      f._equipDart = true;
    } },
  { id:'e_wave', name:'海浪', icon:'equip/dungeon-wave.png', category:'unique',
    desc:'提供 +50 最大生命值, +10% 护盾和治疗强度。\n巨浪:\n携带者每回合末获得 1 层巨浪层数。达到 3 层时, 生成一股巨浪沿一横排移动, 随后重置巨浪层数。\n巨浪使接触的己方单位立即 +20 护盾, 并永久 +2 护甲 / +2 魔抗。\n巨浪使接触的敌方单位受到 20 魔法伤害, 并永久 -2 护甲 / -2 魔抗。',
    apply(f: any) {
      f.maxHp += 50; f.hp += 50;
      // 复用 _equipRippleHealAmp (applyHeal + addShield 都读) — 海浪 +10%, 跟潮汐涟漪叠加
      f._equipRippleHealAmp = (f._equipRippleHealAmp || 0) + 10;
      f._equipWave = true;
      f._equipWaveStacks = 0;
    } },

  // ── Consumables (用完即销毁, 不占装备槽; 当前仅"装备日"模式 + 调试面板加入) ──
  // 字段 target: 'ally' (默认) 拖到友方; 'enemy' 拖到敌方 (像扔炸弹)
  { id:'c_heal', name:'治疗药水', icon:'equip/equip-heal-potion.png', category:'consumable', target:'ally',
    desc:'一次性消耗品。\n拖到友方单位上使用, 立即为该目标回复 (50 + 10% 目标最大生命值) 生命值。使用后装备销毁。',
    apply(f: any) {
      const amt = 50 + Math.round((f.maxHp || 0) * 0.10);
      if (typeof applyHeal === 'function') applyHeal(f, amt, '治疗药水');
      else f.hp = Math.min(f.maxHp || 0, (f.hp || 0) + amt);
    } },
  { id:'c_speed', name:'加速药水', icon:'equip/equip-speed-potion.png', category:'consumable', target:'ally',
    desc:'一次性消耗品。\n拖到友方单位上使用, 该目标所有技能的当前剩余冷却时间 -1 回合 (最低 0)。使用后装备销毁。',
    apply(f: any) {
      if (Array.isArray(f.skills)) {
        for (const s of f.skills) {
          if (s && typeof s.cdLeft === 'number' && s.cdLeft > 0) s.cdLeft = Math.max(0, s.cdLeft - 1);
        }
      }
    } },
  { id:'c_bomb', name:'炸弹', icon:'equip/consumable-bomb.png', category:'consumable', target:'enemy',
    desc:'一次性消耗品。\n拖到敌方单位上使用, 对该目标造成 60 物理伤害 (不归属任何龟, 不触发生命偷取与 on-hit 链, 仅按目标护甲减免)。使用后装备销毁。',
    apply(f: any) {
      // P91 1:1 JS engine.js c_bomb: applyRawDmg(null, f, 60, false, false, 'physical')
      //   PoC top-of-file applyRawDmg stub 是 noop → 炸弹永远 0 伤! (agent audit 发现)
      //   inline 实现: 物理走 def 减免 (1:1 JS engine.js bomb), shield 先吸再 HP
      const baseDmg = 60;
      const def = (f.def ?? 0);
      const mult = def >= 0 ? (1 - def / (def + 100)) : 1 + Math.abs(def) / (Math.abs(def) + 100);
      const final = Math.max(1, Math.round(baseDmg * mult));
      let remaining = final;
      if ((f.shield ?? 0) > 0) {
        const absorbed = Math.min(f.shield, remaining);
        f.shield -= absorbed;
        remaining -= absorbed;
      }
      if (remaining > 0) {
        f.hp = Math.max(0, (f.hp ?? 0) - remaining);
        if (f.hp <= 0) f.alive = false;
      }
    } },

  // ── 商店小商品 → 备战席消耗品 (ally-target 商品改进 bench 拖拽流) ──
  { id:'c_rage', name:'🔥 怒火药水', icon:'equip/consumable-rage.png', category:'consumable', target:'ally',
    desc:'一次性消耗品。\n拖到友方单位上使用, 该目标获得攻击力 +25% buff, 持续 3 回合。使用后装备销毁。',
    apply(f: any) {
      if (!Array.isArray(f.buffs)) f.buffs = [];
      f.buffs.push({ type:'atkUp', value: Math.round((f.baseAtk ?? f.atk ?? 0) * 25 / 100), duration:3 });  // P141b turns→duration; F1 +25%atk 折 flat
      if (typeof recalcStats === 'function') recalcStats();
      if (typeof renderStatusIcons === 'function') renderStatusIcons(f);
    } },
  { id:'c_emergency', name:'⛑ 应急护盾', icon:'equip/consumable-shield.png', category:'consumable', target:'ally',
    desc:'一次性消耗品。\n拖到友方单位上使用, 立即为该目标添加 +80 护盾。使用后装备销毁。',
    apply(f: any) {
      f.shield = (f.shield || 0) + 80;
      if (typeof updateHpBar === 'function' && typeof getFighterElId === 'function') updateHpBar(f, getFighterElId(f));
    } },
  { id:'c_firstaid', name:'🌿 急救包', icon:'equip/consumable-firstaid.png', category:'consumable', target:'ally',
    desc:'一次性消耗品。\n拖到友方单位上使用, 立即为该目标回复 15% 目标最大生命值。使用后装备销毁。',
    apply(f: any) {
      const amt = Math.round((f.maxHp || 0) * 0.15);
      if (typeof applyHeal === 'function') applyHeal(f, amt, '急救包');
      else f.hp = Math.min(f.maxHp || 0, (f.hp || 0) + amt);
    } },
  { id:'c_cleanse', name:'✨ 净化', icon:'equip/consumable-cleanse.png', category:'consumable', target:'ally',
    desc:'一次性消耗品。\n拖到友方单位上使用, 立即清除该目标身上所有负面状态。使用后装备销毁。\n※ 负面效果包括: 灼烧 / 中毒 / 流血 / 诅咒 DoT / 冰寒 / 攻防魔抗削减 / 治疗削减 / 易伤标记 / 泡泡束缚',
    apply(f: any) {
      if (!Array.isArray(f.buffs)) return;
      const debuffTypes = new Set(['dot','burn','poison','bleed','chilled','atkDown','defDown','mrDown','healReduce','markedDmg','bubbleBind']);
      f.buffs = f.buffs.filter((b: any) => !debuffTypes.has(b.type));
      if (typeof renderStatusIcons === 'function') renderStatusIcons(f);
    } },
  { id:'c_mark', name:'🎯 必中标记', icon:'equip/consumable-mark.png', category:'consumable', target:'enemy',
    desc:'一次性消耗品。\n拖到敌方单位上使用, 标记该目标 2 回合, 期间该目标受到的所有伤害 +20% (任何来源)。使用后装备销毁。',
    apply(f: any) {
      if (!Array.isArray(f.buffs)) f.buffs = [];
      f.buffs.push({ type:'markedDmg', value:20, duration:2 });  // P141b turns→duration (之前永不过期, +20%易伤 变永久)
      if (typeof renderStatusIcons === 'function') renderStatusIcons(f);
    } },

  // ── 糖果罐 (糖果龟开局被动放上) ──
  // category:'special' 不入掉落池; actionable:'break' 让 bench UI 不可拖, 改"打碎"按钮.
  // 打碎逻辑在 js/skills/candy.js 里 (breakCandyJar). 这里 apply 留空 — 它不像普通装备
  // 那样"装上就生效", 永远只通过 breakCandyJar 路径开.
  // ── 训龟大师的口哨 (用户新装备 spec) — 特殊物品, 仅中立掉落 / 给装备概率获得, 小商店买不到 ──
  // category:'special' 不入掉落普通池; actionable:'blow' → bench 点击「吹响」(不可拖到龟身上).
  // 吹响后召唤训龟大师登场 4 回合 (占 1 空位, 不可选/不受伤/不造成伤害), 每回合释放 1 种能力.
  { id:'e_master_whistle', name:'训龟大师的口哨', icon:'📯', category:'special', actionable:'blow',
    desc:'特殊物品。\n吹响口哨后, 一名训龟大师登场 4 回合, 其无法被选中、不会受到伤害、也不会造成伤害。期间每回合训龟大师会释放一种能力:\n1. 召唤灵体小龟对随机一行敌人释放龟派气波, 沿途造成三段共 90 物理伤害 (会击飞目标)\n2. 提供一件消耗品与 2 深海币\n3. 提供一件装备\n4. 为一只友方乌龟 (优先最大生命最高) +50 最大生命 / +5 护甲 / +5 魔抗\n5. 为一只友方乌龟 (优先本场输出最高) +15 攻击 / +5 护甲穿透 / +5 魔法穿透\n6. 为友方全场单位提供共 150 永久护盾 (均分)\n7. 为一只友方乌龟 +1 临时等级\n<span style="color:#888;font-size:0.9em">能力 4/5/7 召唤物不算; 仅在己方场上有空位时可吹响; 4 回合后训龟大师消失。特殊物品, 无法在目标上使用。</span>',
    apply(_f: any) { /* no-op: 口哨只能吹响, 不"装备" */ } },

  { id:'c_candy_jar', name:'糖果罐', icon:'equip/equip-candy-jar.png', category:'special', actionable:'break',
    desc:'糖果龟的特殊装备, 任何商店或宝箱都无法获得。\n装备席中点击 "打碎" 按钮即可消耗糖果罐, 并按当前回合数获得一件随机稀有度的装备奖励。\n※ 回合 1~2: 治疗药水或加速药水 (各 50% 概率) 任一种 1 瓶\n※ 回合 3~4: 治疗药水或加速药水 (各 50% 概率) 任一种 1 瓶 + 1 个炸弹\n※ 回合 5~6: 1 个随机消耗品 + 1 件随机装备\n※ 回合 7~9: 2 个随机消耗品 + 1 件随机装备\n※ 回合 10+: 2 个随机消耗品 + 2 件随机装备',
    apply(f: any) { /* no-op: 糖果罐不"装备", 只能打碎 */ } },

  // ── P108: 孵化器 (用户新装备 spec) ──
  // 进度满 100 → 临时等级 +1 (上限 +3), 每级 +5% 基础属性
  // 进度来源 (BattleScene 端 hook 累加 _incubatorProgress):
  //   回合开始 +5 / 敌方死 +10 / 我方死 +15 / 造成伤害 ×0.1 / 承受伤害 ×0.1
  { id:'e_incubator', name:'孵化器', icon:'equip/equip-incubator.png', category:'normal',
    desc:'提供 +20 最大生命值。\n每回合获得孵化进度, 进度满 100 后获得 +1 临时等级 (上限 +3)。\n进度来源: 回合+5, 敌死+10, 我死+15, 造伤×0.1, 承伤×0.1\n<span style="color:#888;font-size:0.9em">每一级提升 5% 基础属性, 临时等级只在这个对局生效</span>',
    apply(f: any) {
      f.maxHp += 20; f.hp += 20;
      // 初始化运行时字段 (BattleScene 端的 onTurnBegin/onDeath/onHit hook 累加)
      f._incubatorProgress = 0;
      f._incubatorTempLevel = 0;   // 0/1/2/3
    } },

  // ── P109: 电棍 (用户新装备 spec) ──
  // 3 层电击层数. 携带者施法后, 单体技能电击 target, 非单体随机电击敌人.
  // 电击 = 30 魔法 + 眩晕 1 回合. 消耗 1 层. 0 层不再触发但装备不消失.
  { id:'e_stun_baton', name:'电棍', icon:'equip/equip-stun-baton.png', category:'normal',
    desc:'提供 +20 最大生命值, +5 护甲, +5 魔抗。\n装备时拥有 3 层电击层数。\n携带者施法后, 若是单体技能则电击该目标, 非单体则随机电击一名敌人, 造成 30 魔法伤害并使其眩晕 1 回合。\n每次电击消耗 1 层电击层数。\n<span style="color:#888;font-size:0.9em">层数为 0 这个装备不会消失</span>',
    apply(f: any) {
      f.maxHp += 20; f.hp += 20;
      f.baseDef += 5; f.def = f.baseDef;
      f.baseMr = (f.baseMr || f.baseDef) + 5; f.mr = f.baseMr;
      f._stunBatonStacks = 3;
    } },

  // ── P110: 竹叶 (用户新装备 spec) ──
  // 1 次生长充能. 施法后强化攻击随机敌人 (35 + 携带者 20% maxHp) 魔法
  // + 回携带者 20% maxHp + 永久 +100 maxHp. 充能消耗后装备不消失.
  { id:'e_bamboo_leaf', name:'竹叶', icon:'equip/equip-bamboo-leaf.png', category:'normal',
    desc:'提供 +50 最大生命值。\n装备时获得一次生长充能。\n施法后附带一发强化攻击, 对随机敌人造成 (35 + 携带者 20% 最大生命值) 魔法伤害, 回复携带者 20% 最大生命值, 并永久增加自身 100 最大生命值。\n<span style="color:#888;font-size:0.9em">消耗这个充能后不会摧毁这件装备</span>',
    apply(f: any) {
      f.maxHp += 50; f.hp += 50;
      f._bambooLeafCharge = 1;
    } },

  // ── 雷电法杖 (用户新装备 spec) ──
  // 携带者每段主动单体伤害 +25 闪电值 (AOE 段 +12.5)。满 100 发射连锁闪电:
  //   朝随机敌人 20 魔法, 在不同目标间跳跃, 最多命中 4 个。满 100 后减 100 保留溢出。
  //   充能+发射逻辑在 passive-triggers.ts triggerOnHitEffects (读 _castIsAoe)。
  { id:'e_lightning_staff', name:'雷电法杖', icon:'equip/equip-lightning-staff.png', category:'normal',
    desc:'提供 +8 魔抗穿透。\n连锁闪电:\n携带者每段单体伤害为这件装备充能 25 闪电值。闪电值满 100 时, 朝随机目标发射连锁闪电, 造成 20 魔法伤害, 闪电在不同目标间跳跃, 最多命中 4 个目标。\n<span style="color:#888;font-size:0.9em">AOE 技能的充能效果为 50%; 满 100 发射后保留溢出充能</span>',
    apply(f: any) {
      f.magicPen = (f.magicPen || 0) + 8;
      f._lightningStaffCharge = f._lightningStaffCharge ?? 0;   // 闪电值 (triggerOnHitEffects 累加)
    } },

  // ── P105: 用户提供的 3 件初始装备 (PVP/野生/深海第一关第一回合 3 选 1) ──

  // 小龟帽: +70 maxHp + 每回合复苏 25 HP
  { id:'e_turtle_helmet', name:'小龟帽', icon:'equip/equip-turtle-helmet.png', category:'initial',
    desc:'提供 +70 最大生命值。\n复苏: 每回合携带者恢复 25 生命值。\n<span style="color:#888;font-size:0.9em">受治疗减益和治疗强度影响</span>',
    apply(f: any) {
      f.maxHp += 70; f.hp += 70;
      f._turtleHelmetRecover = 25;   // 每回合 turn-begin 触发
      f._turtleHelmetHealStat = 0;   // 累计治疗量统计 (灰字)
    } },

  // 小龟剑: +10 ATK + 施法后劈砍目标 30 物理 + 治疗 50% 实际伤害
  { id:'e_turtle_sword', name:'小龟剑', icon:'equip/equip-turtle-sword.png', category:'initial',
    desc:'提供 +10 攻击力。\n劈砍: 携带者施法结束后劈砍目标, 造成 30 物理伤害并治疗携带者相当于实际造成伤害的 50%。\n<span style="color:#888;font-size:0.9em">若是群体技能则优先选择前排</span>',
    apply(f: any) {
      f.baseAtk += 10; f.atk = f.baseAtk;
      f._turtleSword = true;
      f._turtleSwordDmgStat = 0;     // 累计造成伤害
      f._turtleSwordHealStat = 0;    // 累计治疗量
    } },

  // 小龟壳: +5 def +5 mr + 每次受非真伤 -2 (累计统计)
  { id:'e_turtle_shell', name:'小龟壳', icon:'equip/equip-turtle-shell.png', category:'initial',
    desc:'提供 +5 护甲, +5 魔抗。\n格挡: 携带者每次受到的攻击伤害减少 2。\n<span style="color:#888;font-size:0.9em">不包括真实伤害</span>',
    apply(f: any) {
      f.baseDef += 5; f.def = f.baseDef;
      f.baseMr = (f.baseMr || f.baseDef) + 5; f.mr = f.baseMr;
      f._turtleShellBlock = 2;    // 每次受非真伤减 2
      f._turtleShellBlockedStat = 0;   // 累计格挡 (灰字)
    } },
] as unknown as EquipmentDef[];

export const EQUIP_BY_ID: Record<string, EquipmentDef> = Object.fromEntries(
  EQUIP_POOL.map(e => [e.id, e])
);
